### ISSUE TITLE
Can't fetch wren-cli version 0.4.0

### ISSUE THREAD

**Issue by dantecatalfamo** [jtakakura/asdf-wren-cli#1]
**Describe the bug**

As of version 0.4.0 it looks like the zip file has changed from `wren_cli-{platform}-{version}.zip` to `wren-cli-{platform}-{version}.zip`. When the `asdf` plugin goes to fetch the latest release, it tries to download the wrong filename and fails.

**Steps to reproduce**

Run `asdf install wren-cli latest`

**Expected behavior**

`wren-cli` is installed

**Screenshot**

<img width="864" alt="dante@Dantes-MacBook-Pro-2:~ 2022-04-11 15-13-55" src="https://user-images.githubusercontent.com/43040593/162812874-e9fe02d3-9179-452c-98ac-b32286d71100.png">

**Comment by jtakakura** [comment]
@dantecatalfamo I fixed this issue.
Please run the command, `asdf plugin update wren-cli` and try to install again.

**Comment by dantecatalfamo** [comment]
Awesome, thank!
